language: node_js

node_js:
- '8'

script: npm run build

notifications:
  email: false

cache:
  directories:
    - node_modules

after_success:
- npm run codecov

addons:
  chrome: stable

deploy:
  provider: pages
  skip_cleanup: true
  github_token: PpNssK9LEz9DfPR618tB
  local_dir: dist,
  target_branch: gh-pages
  on:
    branch: master

dist: trusty