language: node_js

node_js:
- '8'

script: npm run build

notifications:
  email: false

cache:
  directories:
    - node_modules

after_success:
- npm run codecov

addons:
  chrome: stable

env:
  global:
    - secure: PpNssK9LEz9DfPR618tB
    
deploy:
  provider: pages
  skip_cleanup: true
  github_token: 0b25ee09efffb7dadf2e2460b02cb0d3d4ecdfc9
  local_dir: dist,
  target_branch: gh-pages
  on:
    branch: master

dist: trusty