language: node_js

node_js:
- '8'

script: npm run build

notifications:
  email: false

cache:
  directories:
    - node_modules

after_success:
- npm run codecov

addons:
  chrome: stable

dist: trusty